### ISSUE TITLE
Regarding The Great Card Crash of 9/22

### ISSUE THREAD

**Issue by Tsubami** [lalcmellkmal/cam#24]
Greetings Lal'C

Currently there are a few teams racing to create the first CAM playing bot. For this reason I've been researching what http requests are being exchanged.

While joining a game, the join requests sends a parameter GameID which in normally 1. Changing it, as i expected, led me to a different game room. The problem is that it seems that the join command is the only piece of code that somewhat  supports the idea of rooms, so the reaction of everything else isn't quite predictable which led to the great crash.

To be more precise the problem arises from 3 things. 
1) The only way to join another game room is by joining the game in the room
2) You can only leave the room you are in currently
3) You will be randomly kicked back to room 1 from other rooms
So a person in a game in a room 2 for example after being kicked to room 1, will not be able to return to room 2 since the only way to do so is to join the game in room 2 which he already joined. Since he can't join that room, he can't leave it. Since the game doesn't know how to treat rooms this zombie player is also displayed in room 1. And this zombie player doesn't ever get dropped by the idle system since from rooms 2 point of view, he's not idling, he's the only player. The connection breakers seem to also only operate with room 1, so the zombie doesn't ever leave room 2. The gray zombies probably operate in similar fashion. Chat in other rooms works in mysterious ways which are inconsistent.

P.S.
The last card update went wrong somehow, the cards are on the git, but not in game. The site was down on the day of update so maybe it's that. Or y-you m-might have forgotten to run the u-update script.

P.S.S.
s-sorry for messing up the game

**Comment by lalcmellkmal** [comment]
Thank you for the detailed analysis! I hopefully fixed it by removing the game ID parameter altogether. Yeah, it's a shame that feature was never fully baked.

Let me know if you find any more issues. Thanks again.
